### ISSUE TITLE
标准库 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#13]
https://goa.lenggirl.com/golang/lib.html

**Comment by hunterhug** [comment]
安装docker后，运行hunterhug/gotourzh 可以更加详细地学习。

**Comment by dtonew** [comment]
第三个代码框的最后一行有误，应为
cat,2,3,map[1:s],map[int]string{1:"s"}

**Comment by hunterhug** [comment]
> @dtonew
> 第三个代码框的最后一行有误，应为
> cat,2,3,map[1:s],map[int]string{1:"s"}

修改代码后没有重新运行，实际结果是：

```
fmt.Printf("%s,%d,%s,%v,%#v\n", "cat", 2, "3", map[int]string{1: "s"}, map[int]string{1: "s"})

# output
cat,2,3,map[1:s],map[int]string{1:"s"}
```

`%#v`  会比 `%v` 格式化输出更多的信息。`v` 应该是 `variable` 变量的简称，事前不知道该变量的类型。
