### ISSUE TITLE
包、变量和函数 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#2]
https://goa.lenggirl.com/golang/basic.html

**Comment by hunterhug** [comment]
真棒

**Comment by qingstack** [comment]
阅读感不错，good!

**Comment by hunterhug** [comment]
> @qingstack
> 阅读感不错，good!

Thank you very much. 写得简单了一点。

**Comment by hunterhug** [comment]
Golang会智能进行变量分析。所以有一个叫变量逃逸的说法。

也就是变量被分配到堆里面heap，还是栈里面stack，主要取决于后期该变量会不会继续使用，如果不会，那么就分配到栈里，如果会，分配到堆里。
