### ISSUE TITLE
冒泡排序 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#22]
https://goa.lenggirl.com/algorithm/sort/bubble_sort.html

**Comment by hunterhug** [comment]
冒泡是最简单的排序算法，奥巴马也写过。手写冒泡，是每个大学应届生必经之路。

**Comment by zgaaaa** [comment]
bool变量是不是应该放在外循环内，你这样写，只要第一轮存在交换，bool值就永远是true，起不到判断效果

**Comment by hunterhug** [comment]
> bool变量是不是应该放在外循环内，你这样写，只要第一轮存在交换，bool值就永远是true，起不到判断效果

写得没错，这是对冒泡排序的一种优化：

**Comment by zgaaaa** [comment]
> @hunterhug
> > bool变量是不是应该放在外循环内，你这样写，只要第一轮存在交换，bool值就永远是true，起不到判断效果
> 
> 写得没错，这是对冒泡排序的一种优化：
> 
> 我们引入了 didSwap 的变量，如果在一轮中该变量值没有变化，那么表示数列是有序的，所以不需要交换。也就是说在最好的情况下：对已经排好序的数列进行冒泡排序，只需比较 N 次，最好时间复杂度从 O(n^2) 骤减为 O(n)。

懂了，但是如果一个数列是前半部分是有序的而后半部分是无序的，将didSwap变量放在外循环内就可以减少外循环次数，是不是更优化了

**Comment by hunterhug** [comment]
> > @hunterhug
> > > bool变量是不是应该放在外循环内，你这样写，只要第一轮存在交换，bool值就永远是true，起不到判断效果
> > 
> > 
> > 写得没错，这是对冒泡排序的一种优化：
> > 我们引入了 didSwap 的变量，如果在一轮中该变量值没有变化，那么表示数列是有序的，所以不需要交换。也就是说在最好的情况下：对已经排好序的数列进行冒泡排序，只需比较 N 次，最好时间复杂度从 O(n^2) 骤减为 O(n)。
> 
> 懂了，但是如果一个数列是前半部分是有序的而后半部分是无序的，将didSwap变量放在外循环内就可以减少外循环次数，是不是更优化了

不会更优化了，冒泡排序是交换排序算法，每一轮都是从开头开始交换。加上didSwap，当作一个哨兵，本来应该冒泡N次，但如果第一次哨兵变化了，那么证明数组有序，不需要再冒泡直接返回。

**Comment by zishiguo** [comment]
还有优化的空间
```golang
package main

import "fmt"

func main() {
	//a := []int{5, 9, 1, 6, 8, 14, 6, 49, 25, 4, 6, 3}
	a := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49}
	bubbleSort(a)
	fmt.Println(a)

	//b := []int{5, 9, 1, 6, 8, 14, 6, 49, 25, 4, 6, 3}
	b := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49}
	bubbleSort2(b)
	fmt.Println(b)

	//c := []int{5, 9, 1, 6, 8, 14, 6, 49, 25, 4, 6, 3}
	c := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49}
	bubbleSort3(c)
	fmt.Println(c)

}

func bubbleSort(list []int) {
	n := len(list)
	// 在一轮中有没有交换过
	didSwap := false

	var count1, count2 int
	// 进行 N-1 轮迭代
	for i := n - 1; i > 0; i-- {
		// 每次从第一位开始比较，比较到第 i 位就不比较了，因为前一轮该位已经有序了
		for j := 0; j < i; j++ {
			count1++
			// 如果前面的数比后面的大，那么交换
			if list[j] > list[j+1] {
				count2++
				list[j], list[j+1] = list[j+1], list[j]
				didSwap = true
			}
		}

		// 如果在一轮中没有交换过，那么已经排好序了，直接返回
		if !didSwap {
			fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
			return
		}
	}
	fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
}

func bubbleSort2(a []int) {
	num := len(a)
	var count1, count2 int
	for i := num - 1; i > 0; i-- {
		didSwap := false
		for j := 0; j < i; j++ {
			count1++
			if a[j] > a[j+1] {
				count2++
				a[j], a[j+1] = a[j+1], a[j]
				didSwap = true
			}
		}
		if !didSwap {
			fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
			return
		}
	}
	fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
}

func bubbleSort3(a []int) {
	num := len(a)
	flag := true
	var count1, count2 int
	for i := num - 1; i > 0 && flag; i-- {
		for j := 0; j < i; j++ {
			flag = false
			count1++
			if a[j] > a[j+1] {
				flag = true
				count2++
				a[j], a[j+1] = a[j+1], a[j]
			}
		}
	}
	fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
}

```
输出结果如下:
```
循环了66次，移动了1次
[1 3 4 5 6 6 6 8 9 14 25 49]
循环了21次，移动了1次
[1 3 4 5 6 6 6 8 9 14 25 49]
循环了11次，移动了1次
[1 3 4 5 6 6 6 8 9 14 25 49]
```

**Comment by hunterhug** [comment]
> @zishiguo
> 还有优化的空间
> ```golang
> package main
> 
> import "fmt"
> 
> func main() {
> 	//a := []int{5, 9, 1, 6, 8, 14, 6, 49, 25, 4, 6, 3}
> 	a := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49}
> 	bubbleSort(a)
> 	fmt.Println(a)
> 
> 	//b := []int{5, 9, 1, 6, 8, 14, 6, 49, 25, 4, 6, 3}
> 	b := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49}
> 	bubbleSort2(b)
> 	fmt.Println(b)
> 
> 	//c := []int{5, 9, 1, 6, 8, 14, 6, 49, 25, 4, 6, 3}
> 	c := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49}
> 	bubbleSort3(c)
> 	fmt.Println(c)
> 
> }
> 
> func bubbleSort(list []int) {
> 	n := len(list)
> 	// 在一轮中有没有交换过
> 	didSwap := false
> 
> 	var count1, count2 int
> 	// 进行 N-1 轮迭代
> 	for i := n - 1; i > 0; i-- {
> 		// 每次从第一位开始比较，比较到第 i 位就不比较了，因为前一轮该位已经有序了
> 		for j := 0; j < i; j++ {
> 			count1++
> 			// 如果前面的数比后面的大，那么交换
> 			if list[j] > list[j+1] {
> 				count2++
> 				list[j], list[j+1] = list[j+1], list[j]
> 				didSwap = true
> 			}
> 		}
> 
> 		// 如果在一轮中没有交换过，那么已经排好序了，直接返回
> 		if !didSwap {
> 			fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
> 			return
> 		}
> 	}
> 	fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
> }
> 
> func bubbleSort2(a []int) {
> 	num := len(a)
> 	var count1, count2 int
> 	for i := num - 1; i > 0; i-- {
> 		didSwap := false
> 		for j := 0; j < i; j++ {
> 			count1++
> 			if a[j] > a[j+1] {
> 				count2++
> 				a[j], a[j+1] = a[j+1], a[j]
> 				didSwap = true
> 			}
> 		}
> 		if !didSwap {
> 			fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
> 			return
> 		}
> 	}
> 	fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
> }
> 
> func bubbleSort3(a []int) {
> 	num := len(a)
> 	flag := true
> 	var count1, count2 int
> 	for i := num - 1; i > 0 && flag; i-- {
> 		for j := 0; j < i; j++ {
> 			flag = false
> 			count1++
> 			if a[j] > a[j+1] {
> 				flag = true
> 				count2++
> 				a[j], a[j+1] = a[j+1], a[j]
> 			}
> 		}
> 	}
> 	fmt.Printf("循环了%d次，移动了%d次\n", count1, count2)
> }
> 
> ```
> 输出结果如下:
> ```
> 循环了66次，移动了1次
> [1 3 4 5 6 6 6 8 9 14 25 49]
> 循环了21次，移动了1次
> [1 3 4 5 6 6 6 8 9 14 25 49]
> 循环了11次，移动了1次
> [1 3 4 5 6 6 6 8 9 14 25 49]
> ```

`bubbleSort2` 确实更优化，把哨兵放在了里面。也就是说第一轮如果发现不是顺序的，那么交换后可以在第二轮继续哨兵。

然后 `bubbleSort3` 是有误的。例子：
 
```
        c := []int{3, 1, 4, 5, 6, 6, 6, 8, 9, 14, 25, 49, 1, 2, 3, 4, 5, 6}
	bubbleSort3(c)
	fmt.Println(c)
```

输出:

```
循环了87次，移动了36次
[1 3 4 5 6 6 1 2 3 4 5 6 6 8 9 14 25 49]
```

排序错了。
