### ISSUE TITLE
快速排序 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#28]
https://goa.lenggirl.com/algorithm/sort/quick_sort.html

**Comment by chenfeng99** [comment]
👍

**Comment by zishiguo** [comment]
> * {} --- 基准
> * [] --- 迭代
> * () --- 存储位置

> * {5} ([9]) 1 6 8 14 6 49 25 4 6 3
> * {5} (9) [1] 6 8 14 6 49 25 4 6 3 
> * {5} 1 (9) [6] 8 14 6 49 25 4 6 3 
> * {5} 1 (9) 6 [8] 14 6 49 25 4 6 3  
> * {5} 1 (9) 6 8 [14] 6 49 25 4 6 3 
> * {5} 1 (9) 6 8 14 [6] 49 25 4 6 3 
> * {5} 1 (9) 6 8 14 6 [49] 25 4 6 3  
> * {5} 1 (9) 6 8 14 6 49 [25] 4 6 3 
> * {5} 1 (9) 6 8 14 6 49 25 [4] 6 3 
> * {5} 1 4 (6) 8 14 6 49 25 9 [6] 3 
> * {5} 1 4 (6) 8 14 6 49 25 9 6 [3] 
> * {5} 1 4 3 (8) 14 6 49 25 9 6 6 
> * 3 1 4 {5} 8 14 6 49 25 9 6 6 
```golang
func quickSort(values []int) {
	if len(values) <= 1 {
		return
	}
	pivotIndex := 0
	pivot := values[pivotIndex]
	storeIndex := pivotIndex + 1
	for i := pivotIndex + 1; i < len(values); i++ {
		if values[i] < pivot {
			values[i], values[storeIndex] = values[storeIndex], values[i]
			storeIndex++
		}
	}
	values[pivotIndex], values[storeIndex-1] = values[storeIndex-1], values[pivotIndex]

	quickSort(values[0 : storeIndex-1])
	quickSort(values[storeIndex:])
}
```
