### ISSUE TITLE
分治法和递归 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#51]
https://goa.lenggirl.com/basic/rescuvie.html

**Comment by xuyang404** [comment]
```
// 中间的数比目标还大，从左边找
return BinarySearch(array, target, 1, mid-1)
```
这个1是不是应该改成0才对？不然如果target等于数组第一个数的话就找不到了

**Comment by xuyang404** [comment]
```    
 // 中间的数比目标还大，从左边找
 return BinarySearch(array, target, 1, mid-1)
```

上面的target后面那个参数1应该改为0，不然如果target是数组的第0个元素，会找不到

**Comment by hunterhug** [comment]
> ```
> // 中间的数比目标还大，从左边找
> return BinarySearch(array, target, 1, mid-1)
> ```
> 
> 上面的target后面那个参数1应该改为0，不然如果target是数组的第0个元素，会找不到

是的，会找不到，你发现了一个缺陷。

感谢！！
