### ISSUE TITLE
可变长数组 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#7]
https://goa.lenggirl.com/algorithm/array_change.html

**Comment by xuyang404** [comment]
```
// 新建一个可变长数组
func Make(len, cap int) *Array {
    s := new(Array)
    if len > cap {
        panic("len large than cap")
    }

    // 把切片当数组用
    array := make([]int, cap, cap)

    // 元数据
    s.array = array
    s.cap = cap
    s.len = 0
    return s
}
```

既然基本没用到len，为什么还要传进来呢？

**Comment by hunterhug** [comment]
> ```
> // 新建一个可变长数组
> func Make(len, cap int) *Array {
>     s := new(Array)
>     if len > cap {
>         panic("len large than cap")
>     }
> 
>     // 把切片当数组用
>     array := make([]int, cap, cap)
> 
>     // 元数据
>     s.array = array
>     s.cap = cap
>     s.len = 0
>     return s
> }
> ```
> 
> 既然基本没用到len，为什么还要传进来呢？

确实，可以不传，但是要明确len不能大于cap的思想
