### ISSUE TITLE
列表 · 数据结构和算法（Golang实现）

### ISSUE THREAD

**Issue by hunterhug** [hunterhug/goa.c#9]
https://goa.lenggirl.com/algorithm/list.html

**Comment by xuyang404** [comment]
```
// 是否存在后驱节点
func (node *ListNode) HashNext() bool {
    return node.pre != nil
}

// 是否存在前驱节点
func (node *ListNode) HashPre() bool {
    return node.next != nil
}

```
这段代码是不是有点问题？

**Comment by hunterhug** [comment]
> ```
> // 是否存在后驱节点
> func (node *ListNode) HashNext() bool {
>     return node.pre != nil
> }
> 
> // 是否存在前驱节点
> func (node *ListNode) HashPre() bool {
>     return node.next != nil
> }
> ```
> 
> 这段代码是不是有点问题？

是的，有问题，两个方法名要调转过来。

**Comment by xuyang404** [comment]
```
    // 往后遍历拿到第 N+1 个位置的元素
    for i := 1; i <= n; i++ {
        node = node.next
    }

```
为什么是拿n+1个位置的元素呢？如果总共就3个节点，n又等于3，那取到的node不就是nil了吗？
